Models/cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Solicitacao_de_orcamento.Models
{
    public class cliente
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "O nome do contato deve ser informado.!")]
        [StringLength(50, MinimumLength = 5)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O telefone deve ser informado.!")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Forneça o número do telefone no formato (00) 00000-0000")]
        [DisplayName("Número do Telefone")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "O email é obrigatório!")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DisplayName("Tipo de Projeto")]
        public string TipoProjeto { get; set; }

        [Required(ErrorMessage = "Ínforme a descrição do projeto.")]
        [DisplayName("Descrição do Projeto")]
        [StringLength(5000, MinimumLength = 20)]
        [DataType(DataType.MultilineText)]
        public string Descricao { get; set; }
    }
}

Models/contexto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Solicitacao_de_orcamento.Models
{
    public class contexto: DbContext
    {
        DbSet<cliente> cliente { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Solicitacao_de_orcamento.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Solucoes()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contatos()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/clientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Solicitacao_de_orcamento.Data;
using Solicitacao_de_orcamento.Models;

namespace Solicitacao_de_orcamento.Controllers
{
    public class clientesController : Controller
    {
        private Context db = new Context();

        // GET: clientes
        public ActionResult Index()
        {
            return View(db.clientes.ToList());
        }

        // GET: clientes/Details/5
        public ActionResult Detalhe(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cliente cliente = db.clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: clientes/Create
        public ActionResult Cadastro()
        {
            return View();
        }

        // POST: clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastro([Bind(Include = "Id,Nome,Telefone,Email,TipoProjeto,Descricao")] cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.clientes.Add(cliente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        // GET: clientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cliente cliente = db.clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Telefone,Email,TipoProjeto,Descricao")] cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: clientes/Delete/5
        public ActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cliente cliente = db.clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: clientes/Delete/5
        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cliente cliente = db.clientes.Find(id);
            db.clientes.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/Contatos.cshtml
@{
    ViewBag.Title = "Contatos";
}
<h2>Contatos</h2>
<h3></h3>

<address>
    Bela Vista<br />
    Rua Barata Ribeiro, 1990<br />
    CEP: 01000-000<br />
    <abbr title="Telefone">Em caso de dúvidas, ligue:</abbr>
    3003-0000
</address>

<address>
    <strong>Desenvolvedor:</strong>   <a href="mutuandreoficial@techinova.com">mutuandreoficial@techinova.com</a><br />
    <strong>Marketing:</strong> <a href="tech@techinova.com">tech@techinova.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/1.png" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p class="text-primary">
                    Precisando de um projeto de software. Temos a solução por um preço justo.
                    <a class="btn btn-default" href="/clientes/Cadastro">
                        Solicite aqui!
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/2.jpeg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p class="text-info">
                    Precisando de um projeto de software. Temos a solução por um preço justo.
                    <a class="btn btn-default" href="/clientes/Cadastro">
                        Solicite aqui!
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/4.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p class="text-primary">
                    Precisando de um projeto de software. Temos a solução por um preço justo.
                    <a class="btn btn-default" href="/clientes/Cadastro">
                        Solicite aqui!
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Home/Solucoes.cshtml
@{
    ViewBag.Title = "Soluções";
}
<div class="row">
    <div class="col-md-3">
        <h2>DNA Tecnológico e Inovador</h2>
        <h4>  Conheça nossos produtos</h4>
    </div>
    <div class="col-md-3">
        <h2>CRM</h2>
        <ul>
            <li><a href="https://www.agendor.com.br/blog/software-de-crm/">Principais funcionalidades de um bom software de CRM</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Inteligência Artificial</h2>
        <ul>
            <li><a href="https://www.isbrasil.info/blog/softwares-de-inteligencia-artificial.html">Tecnologias de Inteligência Artificial</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>ERP</h2>
        <ul>
            <li><a href="https://gestaoclick.com.br/erp">ERP para Pequenas e Médias Empresas</a></li>
        </ul>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="~/images/CRM.jpg" alt="...">
            <div class="caption">
                <h3>CRM</h3>
                <p>
                    Quando uma empresa está começando, controlar os e clientes usando planilhas e agendas é possível, ainda que seja comum perder tempo e oportunidades no processo.
À medida que a empresa crescer, no entanto, esse tipo de ferramenta improvisada vai se tornando cada vez mais um empecilho para o sucesso da empresa. Planilhas são difíceis de atualizar, interpretar e compartilhar com o time; anotações e emails acabam perdidos; a comunicação entre vendedores fica prejudicada.
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="~/images/inteligencia.jpg" alt="...">
            <div class="caption">
                <h3>Inteligência Artificial</h3>
                <p>
                    Biometria: esse tipo de software de AI possibilita interações mais naturais entre humanos e máquinas, além de reconhecimento de imagem e toque, fala e linguagem corporal.
                    Automação de processos robóticos: usando scripts e outros métodos para automatizar a ação humana, esses softwares de inteligência artificial criam suporte a projetos de negócio eficientes.
                    A inteligência artificial consiste em um ramo da ciência e da informática que tem como objetivo a criação de máquinas inteligentes. Ela se propõe a desenvolver máquinas que tenham a habilidade de pensar e agir como seres humanos, não necessariamente com um “corpo físico”.
                </p>
            </div>
        </div>
    </div>
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img src="~/images/Erp.png" alt="...">
        <div class="caption">
            <h3>ERP</h3>
            <p>
                Você é daqueles gestores que usa o método “tradicional” de anotar tudo com papel e caneta? A gestão da sua empresa não é digital? Pois saiba que você está complicando a gestão e perdendo uma oportunidade de ouro.
                Hoje em dia existem Sistema ERP completos e integrados, que facilitam a gestão de qualquer negócio, agilizam o serviço e aumentam a produtividade. Um sistema de gestão empresarial é um programa que integra todos os dados e processos de um negócio no mesmo sistema de forma automatizada e organizada.
            </p>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tech Inova</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-fixed-top bg-primary">
        
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tech Inova", "Index", "Home", new { area = "" }, new { @class = "navbar-brand text-white" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Página Inicial", "Index", "Home", new { area = "" }, new { @class = "text-white" })</li>
                    <li>@Html.ActionLink("Soluções", "Solucoes", "Home", new { area = "" }, new { @class = "text-white" })</li>
                    <li>@Html.ActionLink("Contrate", "Index", "clientes", new { area = "" }, new { @class = "text-white" })</li>
                    <li>@Html.ActionLink("Contatos", "Contatos", "Home", new { area = "" }, new { @class = "text-white" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <footer class="foot">
            <hr />
            <p>&copy; @DateTime.Now.Year - Tech Inova</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/clientes/Cadastro.cshtml
@model Solicitacao_de_orcamento.Models.cliente

@{
    ViewBag.Title = "Cadastro";
}

    <h2>Melhore a gestão do seu negócio com a Tech Inova!</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cadastra-se!</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoProjeto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoProjeto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/clientes/Deletar.cshtml
@model Solicitacao_de_orcamento.Models.cliente

@{
    ViewBag.Title = "Deletar";
}

<h2>Eliminar</h2>

<h3>Você tem certeza que quer eliminar?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Views/clientes/Detalhe.cshtml
@model Solicitacao_de_orcamento.Models.cliente

@{
    ViewBag.Title = "Detalhe";
}

    <h2>Melhore a gestão do seu negócio com a Tech Inova!</h2>

<div>
    <h4>Detalhes do cadastro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoProjeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoProjeto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Views/clientes/Edit.cshtml
@model Solicitacao_de_orcamento.Models.cliente

@{
    ViewBag.Title = "Edit";
}

    <h2>Melhore a gestão do seu negócio com a Tech Inova!</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar informações</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoProjeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoProjeto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoProjeto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/clientes/Index.cshtml
@model IEnumerable<Solicitacao_de_orcamento.Models.cliente>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Solicitações</h2>

<p>
    @Html.ActionLink("Cadastrar", "Cadastro")
</p>
<table class="table table-striped">

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoProjeto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td >
            @Html.DisplayFor(modelItem => item.TipoProjeto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Detalhe", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Deletar", new { id=item.Id })
        </td>
    </tr>
}

</table>